### ISSUE TITLE
Create api for backend

### ISSUE THREAD

**Issue by Drego31** [Drego31/harcmap#44]
Create api on frontend for backend:
- [x] sign in
- [x] sign up
- [x] sign out (use mutation `user/signOut`)
- [x] reset password
- [x] points on map
- [x] default settings for map
- [x] collect point

**Comment by HenoJurek** [comment]
Please read [doku](https://github.com/Drego31/harcmap/wiki/Server-(REST)-API-map) and write if you want change something

**Comment by HenoJurek** [comment]
especially please focus on: **longitude, latitude, default_zoom**. I need to know type and examples of values to send you here

**Comment by Drego31** [comment]
> Please read [doku](https://github.com/Drego31/harcmap/wiki/Server-(REST)-API-map) and write if you want change something

OK, I'll check it

> especially please focus on: **longitude, latitude, default_zoom**. I need to know type and examples of values to send you here

- longitude: type number (examples: 54.54355, 158.46346) range from -180 to 180
- latitude: type number (examples: 54.54355, 158.46346) range from -180 to 180
- default_zoom: type number (examples: 12.5, 3.5, 11) range from 2 to 19 (max one decimal number)

**Comment by Drego31** [comment]
I've created mock-api and api on frontend.
